/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hashnotes.ui;

import com.alee.extended.button.WebSplitButton;
import com.alee.extended.button.WebSwitch;
import com.alee.extended.label.WebHotkeyLabel;
import com.alee.laf.button.WebButton;
import com.alee.laf.label.WebLabel;
import com.alee.laf.menu.WebMenuItem;
import com.alee.laf.menu.WebPopupMenu;
import com.alee.managers.hotkey.Hotkey;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JTextPane;

/**
 *
 * @author RESEARCH2
 */
public class JDialogNewNote extends javax.swing.JDialog {

    private int dialogWidth = 0;
    private int dialogHeight = 0;
    private WebMenuItem andTag;
    private WebMenuItem addTag;
    private WebMenuItem excTag;
    public JDialogNewNote(java.awt.Frame parent, boolean modal, int motherLocX, int motherLocY, int motherW) {
        super(parent, modal);
        initComponents();
        dialogHeight = this.getHeight();
        dialogWidth = this.getWidth();
        this.andTag = new WebMenuItem(" & ", Hotkey.ALT_X);
        this.addTag = new WebMenuItem(" + ", Hotkey.D); 
        this.excTag = new WebMenuItem(" ! ", Hotkey.ESCAPE);
       this.setLocation(motherLocX, motherLocY + dialogHeight - 200);
        this.setPreferredSize(new Dimension(motherW, dialogHeight));
        this.revalidate();
        this.pack();
    }

    public WebButton getWebButtonAddNote() {
        return webButtonAddNote;
    }

    public void setWebButtonAddNote(WebButton webButtonAddNote) {
        this.webButtonAddNote = webButtonAddNote;
    }

    public JTextPane getjTextPaneNotes() {
        return jTextPaneNotes;
    }

    public void setjTextPaneNotes(JTextPane jTextPaneNotes) {
        this.jTextPaneNotes = jTextPaneNotes;
    }

    public WebSplitButton getWebSplitButtonTags() {
        return webSplitButtonTags;
    }

    public void setWebSplitButtonTags(WebSplitButton webSplitButtonTags) {
        this.webSplitButtonTags = webSplitButtonTags;
    }

    public WebSwitch getWebSwitchMoreTags() {
        return webSwitchMoreTags;
    }

    public void setWebSwitchMoreTags(WebSwitch webSwitchMoreTags) {
        this.webSwitchMoreTags = webSwitchMoreTags;
    }

    public WebHotkeyLabel getWebHotkeyLabelTags() {
        return webHotkeyLabelTags;
    }

    public void setWebHotkeyLabelTags(WebHotkeyLabel webHotkeyLabelTags) {
        this.webHotkeyLabelTags = webHotkeyLabelTags;
    }

    public WebMenuItem getAndTag() {
        return andTag;
    }

    public void setAndTag(WebMenuItem andTag) {
        this.andTag = andTag;
    }

    public WebMenuItem getAddTag() {
        return addTag;
    }

    public void setAddTag(WebMenuItem addTag) {
        this.addTag = addTag;
    }

    public WebMenuItem getExcTag() {
        return excTag;
    }

    public void setExcTag(WebMenuItem excTag) {
        this.excTag = excTag;
    }

    private WebLabel createSwitchIcon(ImageIcon icon, final int left, final int right) {
        final WebLabel rightComponent = new WebLabel(icon, WebLabel.CENTER);
        rightComponent.setMargin(2, left, 2, right);
        return rightComponent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webMenu1 = new com.alee.laf.menu.WebMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneNotes = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        webSplitButtonTags = new com.alee.extended.button.WebSplitButton();
        webSwitchMoreTags = new com.alee.extended.button.WebSwitch();
        webButtonAddNote = new com.alee.laf.button.WebButton();
        webButton4 = new com.alee.laf.button.WebButton();
        webHotkeyLabelTags = new com.alee.extended.label.WebHotkeyLabel();

        webMenu1.setText("webMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextPaneNotes.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextPaneNotes.setToolTipText("");
        jTextPaneNotes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextPaneNotes);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hashnotes/resources/close (2).png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        webSplitButtonTags.setText("Additional Tags");
        webSplitButtonTags.setEnabled(false);
        webSplitButtonTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webSplitButtonTagsActionPerformed(evt);
            }
        });

        webButtonAddNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hashnotes/resources/add_1.png"))); // NOI18N
        webButtonAddNote.setText("Add");
        webButtonAddNote.setIconTextGap(0);

        webButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hashnotes/resources/close (2).png"))); // NOI18N
        webButton4.setText("Close");
        webButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton4ActionPerformed(evt);
            }
        });

        webHotkeyLabelTags.setText("Tags: / # / @");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(webHotkeyLabelTags, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(webSwitchMoreTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webSplitButtonTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(webButtonAddNote, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(webSplitButtonTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(webButtonAddNote, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(webButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(webHotkeyLabelTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(webSwitchMoreTags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void webSplitButtonTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webSplitButtonTagsActionPerformed
        // Menu for split button
        final WebPopupMenu popupMenu = new WebPopupMenu();
        popupMenu.add( andTag );
        popupMenu.add( addTag);
        popupMenu.addSeparator();
        popupMenu.add( excTag );
        webSplitButtonTags.setPopupMenu(popupMenu);
    }//GEN-LAST:event_webSplitButtonTagsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void webButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_webButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogNewNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogNewNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogNewNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogNewNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogNewNote dialog = new JDialogNewNote(new javax.swing.JFrame(), true, 200, 300, 800);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPaneNotes;
    private com.alee.laf.button.WebButton webButton4;
    private com.alee.laf.button.WebButton webButtonAddNote;
    private com.alee.extended.label.WebHotkeyLabel webHotkeyLabelTags;
    private com.alee.laf.menu.WebMenu webMenu1;
    private com.alee.extended.button.WebSplitButton webSplitButtonTags;
    private com.alee.extended.button.WebSwitch webSwitchMoreTags;
    // End of variables declaration//GEN-END:variables
}
